language: python
cache:
  directories:
    - "$HOME/.cache/pip"

notifications:
  email: false

branches:
  only:
    # Only build master and version tags
    - master
    - /^v\d+\.\d+(\.\d+)?(-\S*)?$/

addons:
  apt:
    packages:
      - libopenblas-base

install:
  - pip3 install pyscf
  - pip3 install --verbose -r requirements.txt
script: python3 setup.py test -a '--cov=adcc'

# These jobs are only run with the first python version
# mentioned in the initial list
jobs:
  include:
    #
    # Checking
    - stage: code style
      python: 3.7
      addons:
        apt:
          packages: []   # Do not install openblas here
      install: travis_retry pip3 install flake8
      script: flake8
      env: CODE_STYLE="flake8"
    #
    # Testing
    - stage: test
      python: 3.7
      env: BUILD_SDIST=true
    - python: 3.5
    - os: osx
      language: script
      osx_image: xcode11.1  # macos 10.14
      env: [CC=gcc-9, CXX=g++-9]

# TODO Does not work at the moment, see the travis output
# https://travis-ci.org/adc-connect/adcc/jobs/603309015#L2647
# after_success:
#    - pip3 install coveralls
#    - coveralls debug --verbose
