name: Publish package
on:
  push:
    branches: [master]
    tags: ['v*']
  workflow_dispatch:

jobs:
  publish_pypi:
    name: Publish 📦 to PyPI
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v1
        with:
          python-version: '3.8'
      - name: Install dependencies
        run: |
          sudo apt-get install libopenblas-base
          python -m pip install --user pyscf cppe wheel
          python -m pip install --user -r requirements.txt
      - name: Run tests
        run: python setup.py test
      - name: Build a source tarball
        run: python setup.py sdist
      - name: Publish distribution 📦 to PyPI
        if: startsWith(github.ref, 'refs/tags')
        uses: pypa/gh-action-pypi-publish@master
        with:
          user: __token__
          password: ${{ secrets.pypi_password }}

  publish_conda:
    name: Publish 📦 to Conda
    needs: publish_pypi
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [macos-latest, ubuntu-latest]

    steps:
    - uses: actions/checkout@v2

    - name: Install deps on macos
      if: contains( matrix.os, 'macos')
      run: brew install coreutils || true
    
    - name: Install macOS SDK
      if: contains( matrix.os, 'macos')
      working-directory: /Users/runner
      run: |
        curl -fsSL https://github.com/phracker/MacOSX-SDKs/releases/download/10.15/MacOSX10.9.sdk.tar.xz > ~/MacOSX10.9.sdk.tar.xz
        tar -xzf ~/MacOSX10.9.sdk.tar.xz
        rm ~/MacOSX10.9.sdk.tar.xz

    - name: Download and verify miniconda
      run: |
        if [[ "${{ matrix.os }}" =~ ^macos ]]; then
            md5sum () { command md5 -r "$@"; }
            MINICONDA=Miniconda3-latest-MacOSX-x86_64.sh
        else
            MINICONDA=Miniconda3-latest-Linux-x86_64.sh
        fi
        MINICONDA_MD5=$(curl -s https://repo.anaconda.com/miniconda/ | grep -A3 $MINICONDA | sed -n '4p' | sed -n 's/ *<td>\(.*\)<\/td> */\1/p')
        curl -fsSL https://repo.anaconda.com/miniconda/$MINICONDA > miniconda.sh
        if [[ $MINICONDA_MD5 != $(md5sum miniconda.sh | cut -d ' ' -f 1) ]]; then
        	echo "Miniconda MD5 mismatch"
        	exit 1
        fi

    - name: Install miniconda
      run: |
        bash miniconda.sh -b -p "$HOME/miniconda"
        rm miniconda.sh

    - name: Build and Deploy
      env:
        ANACONDA_TOKEN: ${{ secrets.ANACONDA_TOKEN }}
      run: |
        source $HOME/miniconda/bin/activate
        bash scripts/upload_to_anaconda.sh
